const $=id=>document.getElementById(id);
let state,pickerTarget,pickerStage=false,generated='';
function button(text,action,cls,label){const b=document.createElement('button');b.textContent=text;b.className=cls??'';if(label)b.setAttribute('aria-label',label);b.onclick=action;return b;}
function select(values,current,label,action){const el=document.createElement('select');el.setAttribute('aria-label',label);for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v;el.append(o);}el.value=current;el.onchange=()=>action(el.value);return el;}
function loadPreset(key){const p=key?structuredClone(presets[key]):{name:'',slot:'Boots',description:'',stack:'1',stats:[],stages:[]};state={details:{DisplayName:p.name,Slot:p.slot,Description:p.description,StackLimit:p.stack,Icon:'',ClassRequired:p.classValue??'',isWeapon:weaponSlots.has(p.slot)},stats:p.stats,stages:p.stages};for(const [key,value] of Object.entries(state.details)){if(key==='isWeapon')$(key).checked=value;else $(key).value=value;}syncWeapon();render();}
function syncWeapon(){const d=state.details;$('ClassRequired').disabled=!d.isWeapon;$('chooseClass').disabled=!d.isWeapon;if(!d.isWeapon){d.ClassRequired='';$('ClassRequired').value='';}$('classHelp').textContent=d.isWeapon?'Weapons only. Choose a class or leave blank for no restriction.':'Only for weapons. Mark this item as a weapon to choose a class.';}
function renderTree(nodes,container,inStage=false,parent='',path='Stats'){container.replaceChildren();if(!nodes.length){const e=document.createElement('div');e.className='empty';e.textContent='No effects yet. Add your first one below.';container.append(e);}nodes.forEach((node,index)=>{const rule=ruleFor(node.key,parent);const wrap=document.createElement('div');wrap.className=node.type==='table'?'tree-table':'effect-row';const row=document.createElement('div');row.className='row';const key=document.createElement('input');key.value=node.key;key.placeholder='Stat key';key.readOnly=!!rule;key.setAttribute('aria-label','Key in '+path);key.oninput=()=>{node.key=key.value;update();};row.append(key);if(rule){const chip=document.createElement('span');chip.className='type-chip';chip.textContent=node.type;row.append(chip);}else row.append(select(['number','boolean','string','table'],node.type,'Value type for '+node.key,type=>{node.type=type;if(type==='table')node.children=[];else node.value=type==='boolean'?'true':type==='number'?'0':'';render();}));if(node.type!=='table'){let value;if(node.type==='boolean')value=select(['true','false'],node.value,'Value for '+node.key,v=>{node.value=v;update();});else if(rule?.choices)value=select(rule.choices,node.value,'Value for '+node.key,v=>{node.value=v;update();});else{value=document.createElement('input');value.value=node.value;value.type=node.type==='number'?'number':'text';if(node.type==='number'){value.step=rule?.integer?'1':'any';if(rule?.min!==undefined)value.min=rule.min;if(rule?.max!==undefined)value.max=rule.max;}value.placeholder='Value';value.setAttribute('aria-label','Value for '+node.key);value.oninput=()=>{node.value=value.value;update();};}row.append(value);}row.append(button('×',()=>{nodes.splice(index,1);render();},'remove','Remove '+node.key));wrap.append(row);if(rule?.help){const help=document.createElement('p');help.className='effect-help';help.textContent=rule.help;wrap.append(help);}if(node.type==='table'){const children=document.createElement('div');children.className='children';const childList=document.createElement('div');renderTree(node.children,childList,inStage,node.key,path+'.'+node.key);children.append(childList,button('＋ Add custom setting',()=>{node.children.push(primitive('CustomSetting',0));render();},'tiny-add'));wrap.append(children);}container.append(wrap);});}
function render(){renderTree(state.stats,$('stats'));$('stages').replaceChildren();if(!state.stages.length){const e=document.createElement('div');e.className='empty';e.textContent='No stages yet. Add a stage to use combat-only effects.';$('stages').append(e);}state.stages.forEach((nodes,i)=>{const card=document.createElement('div');card.className='stage';const head=document.createElement('div');head.className='stage-head';const title=document.createElement('h3');title.textContent='Stage '+(i+1);const path=document.createElement('span');path.className='stage-path';path.textContent='Combat.stage'+(i+1);head.append(title,path,button('×',()=>{state.stages.splice(i,1);render();},'remove','Remove stage '+(i+1)));const list=document.createElement('div');renderTree(nodes,list,true,'','Stats.Combat.stage'+(i+1));card.append(head,list,button('＋ Add stage effect',()=>openPicker(nodes,true),'add'));$('stages').append(card);});$('statCount').textContent=state.stats.length+' fields';$('stageCount').textContent=state.stages.length+' / 10';$('addStage').disabled=state.stages.length>=10;$('addStage').textContent=state.stages.length>=10?'10-stage limit reached':'＋ Add combat stage';update();}
function openPicker(nodes,inStage=false){pickerTarget=nodes;pickerStage=inStage;$('search').value='';$('pickerContext').textContent=inStage?'Adding to a combat stage. Every effect is available.':'Adding to base stats. Combat-only effects are locked here.';renderCatalog('');$('picker').showModal();$('search').focus();}
function addEffect(entry){if(entry.stageOnly&&!pickerStage)return;const fields=entry.make();const existing=new Set(pickerTarget.map(n=>n.key));for(const field of fields)if(!existing.has(field.key))pickerTarget.push(field);$('picker').close();render();}
function renderCatalog(query){const target=$('effectList');target.replaceChildren();const matches=catalog.filter(c=>(c.group+' '+c.key+' '+c.help).toLowerCase().includes(query.toLowerCase()));let group='';for(const c of matches){if(group!==c.group){group=c.group;const h=document.createElement('div');h.className='effect-group';h.textContent=group.toUpperCase();target.append(h);}const b=button('',()=>addEffect(c),'effect-btn');const name=document.createElement('strong');name.textContent=c.key;const help=document.createElement('span');help.textContent=c.help;const content=document.createElement('div');content.append(name,help);b.append(content);const tag=document.createElement('span');const hasAll=c.make().every(n=>pickerTarget.some(p=>p.key===n.key));tag.className='effect-tag';tag.textContent=hasAll?'Added':c.stageOnly&&!pickerStage?'Stage only':'＋';b.append(tag);b.disabled=hasAll||(c.stageOnly&&!pickerStage);target.append(b);}if(!matches.length){const p=document.createElement('p');p.textContent='No matching effects. Add a custom field below.';target.append(p);}}
function paintCode(code){const fragment=document.createDocumentFragment();const regex=/"(?:\\.|[^"\\])*"|\b(?:return|true|false)\b|(?<![\w])[-+]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g;let last=0;for(const match of code.matchAll(regex)){fragment.append(document.createTextNode(code.slice(last,match.index)));const span=document.createElement('span');span.className=match[0].startsWith('"')?'tok-string':/^(return|true|false)$/.test(match[0])?'tok-keyword':'tok-number';span.textContent=match[0];fragment.append(span);last=match.index+match[0].length;}fragment.append(document.createTextNode(code.slice(last)));$('code').replaceChildren(fragment);}
function filename(){return (state.details.DisplayName.replace(/[^a-zA-Z0-9_-]/g,'')||'Item')+'.luau';}
function update(){$('classLabel').textContent=state.details.ClassRequired||'No class restriction';$('slotLabel').textContent=state.details.Slot||'Choose a slot';generated=generate(state);paintCode(generated);const count=generated.split('\n').length;$('numbers').textContent=Array.from({length:count},(_,i)=>i+1).join('\n');$('lineCount').textContent=count+' lines';$('filename').textContent=filename();$('validation').textContent=errors.length?errors[0]+(errors.length>1?' (+'+(errors.length-1)+' more)':''):'Ready to export · No validation errors';$('validation').className=errors.length?'ide-status warning':'ide-status ready';$('validation').title=errors.join('\n');$('copy').disabled=$('download').disabled=!!errors.length;}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2500);}
function addStage(){if(state.stages.length>=10){toast('Maximum 10 combat stages');return;}state.stages.push([]);render();}
for(const id of ['DisplayName','Slot','Description','StackLimit','Icon','ClassRequired'])$(id).addEventListener('input',()=>{state.details[id]=$(id).value;if(id==='Slot'){state.details.isWeapon=weaponSlots.has($(id).value);$('isWeapon').checked=state.details.isWeapon;syncWeapon();}update();});
$('isWeapon').addEventListener('change',()=>{state.details.isWeapon=$('isWeapon').checked;syncWeapon();update();});

$('preset').onchange=()=>loadPreset($('preset').value);
$('new').onclick=()=>{loadPreset(null);$('preset').selectedIndex=-1;$('DisplayName').focus();toast('New item ready');};
$('addStat').onclick=()=>openPicker(state.stats);
$('addStage').onclick=addStage;
$('closePicker').onclick=()=>$('picker').close();
$('picker').addEventListener('click',event=>{if(event.target===$('picker')){const r=$('picker').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('picker').close();}});
$('search').oninput=()=>renderCatalog($('search').value);
$('custom').onclick=()=>{pickerTarget.push(primitive('CustomStat',0));$('picker').close();render();};
$('copy').onclick=async()=>{if(errors.length)return;try{await navigator.clipboard.writeText(generated);toast('Module copied');}catch{const range=document.createRange();range.selectNodeContents($('code'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('Code selected. Press Ctrl+C or ⌘C to copy.');}};
$('download').onclick=()=>{if(errors.length)return;const url=URL.createObjectURL(new Blob([generated+'\n'],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Module downloaded');};
function chooseSlot(slot){slot=slot.trim();if(!slot){toast('Enter a slot name');return;}state.details.Slot=slot;$('Slot').value=slot;state.details.isWeapon=weaponSlots.has(slot);$('isWeapon').checked=state.details.isWeapon;syncWeapon();update();$('slotPicker').close();$('chooseSlot').focus();}
function renderSlots(query=''){const list=$('slotList');list.replaceChildren();let matches=0;const groups=[['Equipment',['Boots','Outfit','Helmet','Gloves']],['Weapons',slotChoices.filter(s=>weaponSlots.has(s))],['Relics & accessories',['Relic','Ring','Amulet','Belt','Cape','Accessory']]];for(const [name,slots] of groups){const found=slots.filter(s=>s.toLowerCase().includes(query.toLowerCase()));if(!found.length)continue;matches+=found.length;const heading=document.createElement('div');heading.className='effect-group';heading.textContent=name;list.append(heading);for(const slot of found){const b=button('',()=>chooseSlot(slot),'effect-btn slot-option');const title=document.createElement('strong');title.textContent=slot;const detail=document.createElement('span');detail.textContent=slot===state.details.Slot?'Selected':weaponSlots.has(slot)?'Weapon slot':'Equipment slot';b.append(title,detail);if(slot===state.details.Slot)b.classList.add('selected');list.append(b);}}if(!matches){const empty=document.createElement('p');empty.className='empty';empty.textContent='No matching slots. Enter a custom slot below.';list.append(empty);}}
$('chooseSlot').onclick=()=>{$('slotSearch').value='';$('customSlot').value='';renderSlots();$('slotPicker').showModal();$('slotSearch').focus();};
$('closeSlots').onclick=()=>$('slotPicker').close();
$('slotSearch').oninput=()=>renderSlots($('slotSearch').value);
$('customSlotForm').addEventListener('submit',event=>{event.preventDefault();chooseSlot($('customSlot').value);});
$('slotPicker').addEventListener('click',event=>{if(event.target===$('slotPicker')){const r=$('slotPicker').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('slotPicker').close();}});
function chooseClass(value){if(!state.details.isWeapon)return;state.details.ClassRequired=value.trim();$('ClassRequired').value=state.details.ClassRequired;update();$('classPicker').close();$('chooseClass').focus();}
function renderClasses(query=''){const list=$('classList');list.replaceChildren();const options=['',...classChoices].filter(c=>(c||'No class restriction').toLowerCase().includes(query.toLowerCase()));for(const value of options){const b=button('',()=>chooseClass(value),'effect-btn slot-option');const name=document.createElement('strong');name.textContent=value||'No class restriction';const note=document.createElement('span');note.textContent=value===state.details.ClassRequired?'Selected':value?'Weapon class':'All classes';b.append(name,note);if(value===state.details.ClassRequired)b.classList.add('selected');list.append(b);}if(!options.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='No matching classes. Enter a custom class below.';list.append(empty);}}
$('chooseClass').onclick=()=>{if(!state.details.isWeapon)return;$('classSearch').value='';$('customClass').value='';renderClasses();$('classPicker').showModal();$('classSearch').focus();};
$('closeClasses').onclick=()=>$('classPicker').close();
$('classSearch').oninput=()=>renderClasses($('classSearch').value);
$('customClassForm').addEventListener('submit',event=>{event.preventDefault();const value=$('customClass').value.trim();if(!value){toast('Enter a class name');return;}chooseClass(value);});
$('classPicker').addEventListener('click',event=>{if(event.target===$('classPicker')){const r=$('classPicker').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('classPicker').close();}});
loadPreset('cinder');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_item_module',title:'Get item module',description:'Read the current item as a Luau module and return validation errors.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({code:generate(state),errors:[...errors],filename:filename()})})).catch(()=>{});}catch{}}
